import type { Metadata } from "next";

import Navbar from "../component/navbar";
import Footer from "@/component/footer";
import "./globals.css";

import { Big_Shoulders, Geist } from "next/font/google";

const bigShoulders = Big_Shoulders({
  subsets: ["latin"],
  variable: "--font-big-shoulders",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Portfolio-Aman",
  description: "Generated by create next app",
  icons: {
    icon: "/images/fasdfa.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bigShoulders.variable} ${geist.variable}   h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
